### ISSUE TITLE
Routing fails without coordinate

### ISSUE THREAD

**Issue by troknil** [erlenddahl/routing#1]
## GET /api/v1/routing

If input is the example 
```
{
  "waypoints": [
    { "x": 271047.81, "y": 7039885.66 },
    { "x": 269319.20, "y": 7039903.40 }
  ]
}
```

The response gives **200 ok** but the result is:
```
{
  "distanceM": 0,
  "sourceSrid": 0,
  "outputSrid": 0,
  "errorMessage": "Object reference not set to an instance of an object."
}
```

Seems to require the `response.coordinates` param to be set. Ie. this works:
```
{
"response": {
    "coordinates": true
  },
  "waypoints": [
    { "x": 271047.81, "y": 7039885.66 },
    { "x": 269319.20, "y": 7039903.40 }
  ]
}
```

The main problem is the 200 OK for an error, it makes it hard to validate if the routing was successful :)

-Trond (Swipload)

**Comment by erlenddahl** [comment]
Thanks, I'll check it out and come back to you.

**Comment by erlenddahl** [comment]
This seems to be resolved in the newest version.
